export const dataDummy1 = {
  istilah: 'badai guntur',
  entri: 'badai1 » badai guntur',
  bentukTidakBaku: 'madaliun',
  kataTurunan: ['burung-burungan', 'ayam-ayaman', 'sapi-sapian'],
  gabunganKata: [
    'burung alau',
    'burung arboreal',
    'burung buaya',
    'burung butbut',
    'burung cabai',
    'burung culik',
    'burung dara laut',
    'burung dewata',
    'burung foniks',
    'burung hantu',
    'burung hantu mulut kodok',
    'burung hiburan',
    'burung kuak',
    'burung kuak-kuak',
    'burung kuar',
    'burung kuaran',
    'burung kumkum',
    'burung laut',
    'burung layang-layang',
    'burung lilin',
    'burung limbuk',
    'burung madu',
    'burung maleo',
    'burung master',
  ],
  peribahasa: ['berkemudi di haluan, bergilir ke buritan'],
  etimologi: {
    bahasaAsal: 'Sanskerta',
    arti: 'waktu, musim, interval, batas',
    kataAsal: 'velā',
  },
  data: [
    {
      lema: 'badai1 » badai guntur',
      arti: [
        {
          kelas_kata: 'Met[Meteorologi: -]',
          deskripsi:
            'badai lokal yang ditimbulkan oleh awan kumulonimbus dan selalu disertai dengan kilat dan guntur',
        },
        {
          kelas_kata: 'Met[Meteorologi: -]',
          deskripsi:
            'pelepasan muatan listrik secara mendadak di udara satu kali atau lebih yang ditandai dengan kilatan cahaya dan disertai bunyi guntur',
        },
      ],
    },
  ],
};

export const dataDummy = {
  istilah: 'bahasa',
  entri: 'ba.ha.sa1',
  bentukTidakBaku: 'basa1',
  kataTurunan: [
    'berbahasa',
    'berbahasa-bahasa',
    'kebahasaan',
    'membahasakan',
    'memperbahasakan',
    'perbahasa',
    'perbahasaan',
    'sebahasa',
  ],
  gabunganKata: [
    'bahasa aglutinatif',
    'bahasa akusatif',
    'bahasa alamiah',
    'bahasa algoritmik',
    'bahasa aljabar',
    'bahasa analitis',
    'bahasa aplikasi',
    'bahasa aplikatif',
    'bahasa asing',
    'bahasa bagongan',
    'bahasa baku',
    'bahasa bangsawan',
    'bahasa berfleksi',
    'bahasa bermajas',
    'bahasa berorientasi aplikasi',
    'bahasa buatan',
    'bahasa buku',
    'bahasa bunga',
    'bahasa campuran',
    'bahasa cinta',
    'bahasa daerah',
    'bahasa dagang',
    'bahasa dalam',
    'bahasa definisi data',
    'bahasa diinterpretasikan',
    'bahasa ergatif',
    'bahasa etalon',
    'bahasa flektif',
    'bahasa gaul',
    'bahasa generasi kedua',
    'bahasa generasi keempat',
    'bahasa generasi kelima',
    'bahasa generasi ketiga',
    'bahasa generasi pertama',
    'bahasa grafik',
    'bahasa gunung',
    'bahasa halus',
    'bahasa hantu',
    'bahasa hibrida',
    'bahasa hidup',
    'bahasa ibu',
    'bahasa ilmu',
    'bahasa imigran',
    'bahasa induk',
    'bahasa inflektif',
    'bahasa inkorporatif',
    'bahasa isolatif',
    'bahasa isyarat',
    'bahasa Jawi',
    'bahasa jurnalistik',
    'bahasa kacukan',
    'bahasa kalangan',
    'bahasa kanak-kanak',
    'bahasa kasar',
    'bahasa kawat',
    'bahasa kebangsaan',
    'bahasa kebun binatang',
    'bahasa kedua',
    'bahasa kentum',
    'bahasa kerabat',
    'bahasa kesat',
    'bahasa kiasan',
    'bahasa klasik',
    'bahasa komputer',
    'bahasa konsonantis',
    'bahasa kuno',
    'bahasa laut',
    'bahasa level rendah',
    'bahasa level sangat tinggi',
    'bahasa level tinggi',
    'bahasa lingo',
    'bahasa lisan',
    'bahasa liturgis',
    'bahasa madya',
    'bahasa markah',
    'bahasa markah hiperteks',
    'bahasa mati',
    'bahasa mendaki',
    'bahasa mendatar',
    'bahasa menurun',
    'bahasa mesin',
    'bahasa modern',
    'bahasa moyang',
    'bahasa nasional',
    'bahasa negara',
    'bahasa oksitonis',
    'bahasa paroksitonis',
    'bahasa pasar',
    'bahasa pembangkit aplikasi',
    'bahasa pemrograman',
    'bahasa pemrograman level tinggi',
    'bahasa pemrograman prosedural',
    'bahasa pemrograman rakit',
    'bahasa pengantar',
    'bahasa pengguna akhir',
    'bahasa perantara',
    'bahasa percakapan',
    'bahasa peringkat tinggi',
    'bahasa perintah',
    'bahasa permintaan',
    'bahasa pers',
    'bahasa persatuan',
    'bahasa pinggiran',
    'bahasa planet',
    'bahasa politik',
    'bahasa portabel',
    'bahasa program',
    'bahasa prokem',
    'bahasa prosedural',
    'bahasa purba',
    'bahasa rakit',
    'bahasa rakitan',
    'bahasa remaja',
    'bahasa resmi',
    'bahasa roh',
    'bahasa santai',
    'bahasa sasaran',
    'bahasa satem',
    'bahasa sedang',
    'bahasa sehari-hari',
    'bahasa semu',
    'bahasa silih',
    'bahasa simbolik',
    'bahasa sintetis',
    'bahasa slang',
    'bahasa sopan santun',
    'bahasa standar',
    'bahasa sulung',
    'bahasa sumber',
    'bahasa tarzan',
    'bahasa teknis',
    'bahasa terbalik',
    'bahasa tingkat rendah',
    'bahasa tonal',
    'bahasa tubuh',
    'bahasa tulis',
    'bahasa tutur',
    'bahasa umum',
    'bahasa visual',
    'bahasa vokalis',
  ],
  peribahasa: ['bahasa menunjukkan bangsa', 'tong kosong nyaring bunyinya'],
  etimologi: {
    bahasaAsal: 'Sanskerta',
    arti: 'ucapan; bahasa',
    kataAsal: 'bhāṣā',
  },
  data: [
    {
      lema: 'ba.ha.sa1',
      arti: [
        {
          kelas_kata: 'n[Nomina: kata benda] Ling[Linguistik: -]',
          deskripsi:
            'sistem lambang bunyi yang arbitrer, yang digunakan oleh anggota suatu masyarakat untuk bekerja sama, berinteraksi, dan mengidentifikasikan diri',
        },
        {
          kelas_kata: 'n[Nomina: kata benda]',
          deskripsi:
            'percakapan (perkataan) yang baik; tingkah laku yang baik; sopan santun: baik budi --nya',
        },
        {
          kelas_kata: 'n[Nomina: kata benda] Komp[Komputer: -]',
          deskripsi:
            'sistem kata atau simbol yang memungkinkan untuk berkomunikasi dengan komputer, terutama untuk memasukkan instruksi-instruksi komputer melalui kata-kata yang mudah dipahami, dan kemudian diterjemahkan ke dalam kode mesin',
        },
      ],
    },
    {
      lema: 'ba.ha.sa2 bentuk tidak baku: basa1',
      arti: [
        {
          kelas_kata:
            'p[Partikel: kelas kata yang meliputi kata depan, kata penghubung, kata seru, kata sandang, ucapan salam] Mk[Minangkabau: -]',
          deskripsi:
            'kata yang digunakan untuk menghubungkan bagian ujaran: dia menerangkan -- dia berasal dari keluarga baik-baik',
        },
      ],
    },
    {
      lema: 'ba.ha.sa3',
      arti: [
        {
          kelas_kata:
            'a[Adjektiva: kata yang menjelaskan nomina atau pronomina]',
          deskripsi:
            'sedikit: angin berembus sepoi-sepoi -- (perlahan-lahan dan silir-semilir); rambutnya kusut-kusut -- (agak kusut)',
        },
      ],
    },
  ],
};
